// worker.proto – bidirectional gRPC stream between WorkerGateway (control-plane)
// and worker daemons.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: worker.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerGateway_Register_FullMethodName      = "/worker.v1.WorkerGateway/Register"
	WorkerGateway_CommandStream_FullMethodName = "/worker.v1.WorkerGateway/CommandStream"
)

// WorkerGatewayClient is the client API for WorkerGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerGatewayClient interface {
	// Register is called once by a new worker at bootstrap time.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// CommandStream is a long-lived bidirectional stream.
	// The worker initiates the stream and sends CommandResult messages;
	// the control plane sends Command messages.
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResult, Command], error)
}

type workerGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerGatewayClient(cc grpc.ClientConnInterface) WorkerGatewayClient {
	return &workerGatewayClient{cc}
}

func (c *workerGatewayClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerGateway_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerGatewayClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResult, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerGateway_ServiceDesc.Streams[0], WorkerGateway_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandResult, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerGateway_CommandStreamClient = grpc.BidiStreamingClient[CommandResult, Command]

// WorkerGatewayServer is the server API for WorkerGateway service.
// All implementations must embed UnimplementedWorkerGatewayServer
// for forward compatibility.
type WorkerGatewayServer interface {
	// Register is called once by a new worker at bootstrap time.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// CommandStream is a long-lived bidirectional stream.
	// The worker initiates the stream and sends CommandResult messages;
	// the control plane sends Command messages.
	CommandStream(grpc.BidiStreamingServer[CommandResult, Command]) error
	mustEmbedUnimplementedWorkerGatewayServer()
}

// UnimplementedWorkerGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerGatewayServer struct{}

func (UnimplementedWorkerGatewayServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerGatewayServer) CommandStream(grpc.BidiStreamingServer[CommandResult, Command]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedWorkerGatewayServer) mustEmbedUnimplementedWorkerGatewayServer() {}
func (UnimplementedWorkerGatewayServer) testEmbeddedByValue()                       {}

// UnsafeWorkerGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerGatewayServer will
// result in compilation errors.
type UnsafeWorkerGatewayServer interface {
	mustEmbedUnimplementedWorkerGatewayServer()
}

func RegisterWorkerGatewayServer(s grpc.ServiceRegistrar, srv WorkerGatewayServer) {
	// If the following call panics, it indicates UnimplementedWorkerGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerGateway_ServiceDesc, srv)
}

func _WorkerGateway_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerGatewayServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerGateway_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerGatewayServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerGateway_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerGatewayServer).CommandStream(&grpc.GenericServerStream[CommandResult, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerGateway_CommandStreamServer = grpc.BidiStreamingServer[CommandResult, Command]

// WorkerGateway_ServiceDesc is the grpc.ServiceDesc for WorkerGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.v1.WorkerGateway",
	HandlerType: (*WorkerGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerGateway_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _WorkerGateway_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "worker.proto",
}
