// worker.proto – bidirectional gRPC stream between WorkerGateway (control-plane)
// and worker daemons.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: worker.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED       CommandType = 0
	CommandType_COMMAND_TYPE_LIST_IMAGES       CommandType = 1
	CommandType_COMMAND_TYPE_PULL_IMAGE        CommandType = 2
	CommandType_COMMAND_TYPE_LIST_PODS         CommandType = 3
	CommandType_COMMAND_TYPE_CREATE_POD        CommandType = 4
	CommandType_COMMAND_TYPE_DELETE_POD        CommandType = 5
	CommandType_COMMAND_TYPE_STOP_POD          CommandType = 6
	CommandType_COMMAND_TYPE_START_POD         CommandType = 7
	CommandType_COMMAND_TYPE_INSPECT_POD       CommandType = 8
	CommandType_COMMAND_TYPE_POD_EXISTS        CommandType = 9
	CommandType_COMMAND_TYPE_POD_LOGS          CommandType = 10
	CommandType_COMMAND_TYPE_GET_POD_RESOURCES CommandType = 11
	CommandType_COMMAND_TYPE_LIST_SECRETS      CommandType = 12
	CommandType_COMMAND_TYPE_DELETE_SECRET     CommandType = 13
	CommandType_COMMAND_TYPE_SECRET_EXISTS     CommandType = 14
	CommandType_COMMAND_TYPE_DELETE_VOLUME     CommandType = 15
	CommandType_COMMAND_TYPE_VOLUME_EXISTS     CommandType = 16
	CommandType_COMMAND_TYPE_INSPECT_CONTAINER CommandType = 17
	CommandType_COMMAND_TYPE_CONTAINER_EXISTS  CommandType = 18
	CommandType_COMMAND_TYPE_CONTAINER_LOGS    CommandType = 19
	CommandType_COMMAND_TYPE_LIST_ROUTES       CommandType = 20
	CommandType_COMMAND_TYPE_DELETE_PVCS       CommandType = 21
	CommandType_COMMAND_TYPE_GET_SYSTEM_INFO   CommandType = 22
	CommandType_COMMAND_TYPE_RUNTIME_TYPE      CommandType = 23
	CommandType_COMMAND_TYPE_EXEC_IN_CONTAINER CommandType = 24
	// Caddy proxy management on the worker node.
	// A single command covers all route operations; the op is encoded in the payload.
	CommandType_COMMAND_TYPE_PROXY_ROUTE    CommandType = 25
	CommandType_COMMAND_TYPE_DOWNLOAD_MODEL CommandType = 27
	// HTTP proxy tunnel through the gRPC stream.
	// The control plane sends an HTTP request; the worker executes it locally
	// against a pod endpoint and returns the response.
	CommandType_COMMAND_TYPE_HTTP_PROXY CommandType = 26
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_TYPE_UNSPECIFIED",
		1:  "COMMAND_TYPE_LIST_IMAGES",
		2:  "COMMAND_TYPE_PULL_IMAGE",
		3:  "COMMAND_TYPE_LIST_PODS",
		4:  "COMMAND_TYPE_CREATE_POD",
		5:  "COMMAND_TYPE_DELETE_POD",
		6:  "COMMAND_TYPE_STOP_POD",
		7:  "COMMAND_TYPE_START_POD",
		8:  "COMMAND_TYPE_INSPECT_POD",
		9:  "COMMAND_TYPE_POD_EXISTS",
		10: "COMMAND_TYPE_POD_LOGS",
		11: "COMMAND_TYPE_GET_POD_RESOURCES",
		12: "COMMAND_TYPE_LIST_SECRETS",
		13: "COMMAND_TYPE_DELETE_SECRET",
		14: "COMMAND_TYPE_SECRET_EXISTS",
		15: "COMMAND_TYPE_DELETE_VOLUME",
		16: "COMMAND_TYPE_VOLUME_EXISTS",
		17: "COMMAND_TYPE_INSPECT_CONTAINER",
		18: "COMMAND_TYPE_CONTAINER_EXISTS",
		19: "COMMAND_TYPE_CONTAINER_LOGS",
		20: "COMMAND_TYPE_LIST_ROUTES",
		21: "COMMAND_TYPE_DELETE_PVCS",
		22: "COMMAND_TYPE_GET_SYSTEM_INFO",
		23: "COMMAND_TYPE_RUNTIME_TYPE",
		24: "COMMAND_TYPE_EXEC_IN_CONTAINER",
		25: "COMMAND_TYPE_PROXY_ROUTE",
		27: "COMMAND_TYPE_DOWNLOAD_MODEL",
		26: "COMMAND_TYPE_HTTP_PROXY",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":       0,
		"COMMAND_TYPE_LIST_IMAGES":       1,
		"COMMAND_TYPE_PULL_IMAGE":        2,
		"COMMAND_TYPE_LIST_PODS":         3,
		"COMMAND_TYPE_CREATE_POD":        4,
		"COMMAND_TYPE_DELETE_POD":        5,
		"COMMAND_TYPE_STOP_POD":          6,
		"COMMAND_TYPE_START_POD":         7,
		"COMMAND_TYPE_INSPECT_POD":       8,
		"COMMAND_TYPE_POD_EXISTS":        9,
		"COMMAND_TYPE_POD_LOGS":          10,
		"COMMAND_TYPE_GET_POD_RESOURCES": 11,
		"COMMAND_TYPE_LIST_SECRETS":      12,
		"COMMAND_TYPE_DELETE_SECRET":     13,
		"COMMAND_TYPE_SECRET_EXISTS":     14,
		"COMMAND_TYPE_DELETE_VOLUME":     15,
		"COMMAND_TYPE_VOLUME_EXISTS":     16,
		"COMMAND_TYPE_INSPECT_CONTAINER": 17,
		"COMMAND_TYPE_CONTAINER_EXISTS":  18,
		"COMMAND_TYPE_CONTAINER_LOGS":    19,
		"COMMAND_TYPE_LIST_ROUTES":       20,
		"COMMAND_TYPE_DELETE_PVCS":       21,
		"COMMAND_TYPE_GET_SYSTEM_INFO":   22,
		"COMMAND_TYPE_RUNTIME_TYPE":      23,
		"COMMAND_TYPE_EXEC_IN_CONTAINER": 24,
		"COMMAND_TYPE_PROXY_ROUTE":       25,
		"COMMAND_TYPE_DOWNLOAD_MODEL":    27,
		"COMMAND_TYPE_HTTP_PROXY":        26,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerName     string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	PreSharedToken string                 `protobuf:"bytes,2,opt,name=pre_shared_token,json=preSharedToken,proto3" json:"pre_shared_token,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// runtime_type declares the execution environment of the worker
	// (e.g. "podman", "openshift"). The control plane persists this to the DB.
	RuntimeType   string `protobuf:"bytes,4,opt,name=runtime_type,json=runtimeType,proto3" json:"runtime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *RegisterRequest) GetPreSharedToken() string {
	if x != nil {
		return x.PreSharedToken
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetRuntimeType() string {
	if x != nil {
		return x.RuntimeType
	}
	return ""
}

type RegisterResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkerName string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	// tls_cert_pem / tls_key_pem are reserved for future mTLS support.
	TlsCertPem    string `protobuf:"bytes,2,opt,name=tls_cert_pem,json=tlsCertPem,proto3" json:"tls_cert_pem,omitempty"`
	TlsKeyPem     string `protobuf:"bytes,3,opt,name=tls_key_pem,json=tlsKeyPem,proto3" json:"tls_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *RegisterResponse) GetTlsCertPem() string {
	if x != nil {
		return x.TlsCertPem
	}
	return ""
}

func (x *RegisterResponse) GetTlsKeyPem() string {
	if x != nil {
		return x.TlsKeyPem
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=worker.v1.CommandType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded type-specific payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded response payload
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	IsHeartbeat   bool                   `protobuf:"varint,5,opt,name=is_heartbeat,json=isHeartbeat,proto3" json:"is_heartbeat,omitempty"`
	WorkerName    string                 `protobuf:"bytes,6,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"` // set on first result and every heartbeat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetIsHeartbeat() bool {
	if x != nil {
		return x.IsHeartbeat
	}
	return false
}

func (x *CommandResult) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\tworker.v1\"\x82\x02\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12(\n" +
	"\x10pre_shared_token\x18\x02 \x01(\tR\x0epreSharedToken\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.worker.v1.RegisterRequest.MetadataEntryR\bmetadata\x12!\n" +
	"\fruntime_type\x18\x04 \x01(\tR\vruntimeType\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12 \n" +
	"\ftls_cert_pem\x18\x02 \x01(\tR\n" +
	"tlsCertPem\x12\x1e\n" +
	"\vtls_key_pem\x18\x03 \x01(\tR\ttlsKeyPem\"n\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.worker.v1.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xb6\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\fis_heartbeat\x18\x05 \x01(\bR\visHeartbeat\x12\x1f\n" +
	"\vworker_name\x18\x06 \x01(\tR\n" +
	"workerName*\xf1\x06\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COMMAND_TYPE_LIST_IMAGES\x10\x01\x12\x1b\n" +
	"\x17COMMAND_TYPE_PULL_IMAGE\x10\x02\x12\x1a\n" +
	"\x16COMMAND_TYPE_LIST_PODS\x10\x03\x12\x1b\n" +
	"\x17COMMAND_TYPE_CREATE_POD\x10\x04\x12\x1b\n" +
	"\x17COMMAND_TYPE_DELETE_POD\x10\x05\x12\x19\n" +
	"\x15COMMAND_TYPE_STOP_POD\x10\x06\x12\x1a\n" +
	"\x16COMMAND_TYPE_START_POD\x10\a\x12\x1c\n" +
	"\x18COMMAND_TYPE_INSPECT_POD\x10\b\x12\x1b\n" +
	"\x17COMMAND_TYPE_POD_EXISTS\x10\t\x12\x19\n" +
	"\x15COMMAND_TYPE_POD_LOGS\x10\n" +
	"\x12\"\n" +
	"\x1eCOMMAND_TYPE_GET_POD_RESOURCES\x10\v\x12\x1d\n" +
	"\x19COMMAND_TYPE_LIST_SECRETS\x10\f\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_DELETE_SECRET\x10\r\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_SECRET_EXISTS\x10\x0e\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_DELETE_VOLUME\x10\x0f\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_VOLUME_EXISTS\x10\x10\x12\"\n" +
	"\x1eCOMMAND_TYPE_INSPECT_CONTAINER\x10\x11\x12!\n" +
	"\x1dCOMMAND_TYPE_CONTAINER_EXISTS\x10\x12\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_CONTAINER_LOGS\x10\x13\x12\x1c\n" +
	"\x18COMMAND_TYPE_LIST_ROUTES\x10\x14\x12\x1c\n" +
	"\x18COMMAND_TYPE_DELETE_PVCS\x10\x15\x12 \n" +
	"\x1cCOMMAND_TYPE_GET_SYSTEM_INFO\x10\x16\x12\x1d\n" +
	"\x19COMMAND_TYPE_RUNTIME_TYPE\x10\x17\x12\"\n" +
	"\x1eCOMMAND_TYPE_EXEC_IN_CONTAINER\x10\x18\x12\x1c\n" +
	"\x18COMMAND_TYPE_PROXY_ROUTE\x10\x19\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_DOWNLOAD_MODEL\x10\x1b\x12\x1b\n" +
	"\x17COMMAND_TYPE_HTTP_PROXY\x10\x1a2\x97\x01\n" +
	"\rWorkerGateway\x12C\n" +
	"\bRegister\x12\x1a.worker.v1.RegisterRequest\x1a\x1b.worker.v1.RegisterResponse\x12A\n" +
	"\rCommandStream\x12\x18.worker.v1.CommandResult\x1a\x12.worker.v1.Command(\x010\x01BFZDgithub.com/project-ai-services/ai-services/internal/pkg/worker/protob\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_worker_proto_goTypes = []any{
	(CommandType)(0),         // 0: worker.v1.CommandType
	(*RegisterRequest)(nil),  // 1: worker.v1.RegisterRequest
	(*RegisterResponse)(nil), // 2: worker.v1.RegisterResponse
	(*Command)(nil),          // 3: worker.v1.Command
	(*CommandResult)(nil),    // 4: worker.v1.CommandResult
	nil,                      // 5: worker.v1.RegisterRequest.MetadataEntry
}
var file_worker_proto_depIdxs = []int32{
	5, // 0: worker.v1.RegisterRequest.metadata:type_name -> worker.v1.RegisterRequest.MetadataEntry
	0, // 1: worker.v1.Command.type:type_name -> worker.v1.CommandType
	1, // 2: worker.v1.WorkerGateway.Register:input_type -> worker.v1.RegisterRequest
	4, // 3: worker.v1.WorkerGateway.CommandStream:input_type -> worker.v1.CommandResult
	2, // 4: worker.v1.WorkerGateway.Register:output_type -> worker.v1.RegisterResponse
	3, // 5: worker.v1.WorkerGateway.CommandStream:output_type -> worker.v1.Command
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
