apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "opensearch"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: vectordb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      ai-services.io/application: {{ .Release.Name }}
      ai-services.io/component: vectordb
