worker:
  image: icr.io/ai-services-cicd/ai-services:v0.0.329
  runtime: "openshift"
  token: ""
  gatewayAddr: ""
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  tls:
    storage: 10Mi
