apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: instruct
  annotations:
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: cluster-local
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - '--tensor-parallel-size=4 '
      - '--max-model-len=32768 '
      - --max-num-seqs=32
      - --served-model-name=ibm-granite/granite-3.3-8b-instruct
      env:
      - name: VLLM_SPYRE_USE_CB
        value: "1"
      modelFormat:
        name: vLLM
      resources:
        limits:
          cpu: "12"
          memory: "150Gi"
          ibm.com/spyre_pf: "4"
        requests:
          cpu: "12"
          memory: "150Gi"
          ibm.com/spyre_pf: "4"
      runtime: spyre-temp
      storageUri: {{ .Values.instruct.storageUri }}
