apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: reranker
  annotations:
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: cluster-local
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      env:
        - name: VLLM_SPYRE_WARMUP_BATCH_SIZES
          value: "4"
        - name: VLLM_SPYRE_WARMUP_PROMPT_LENS
          value: "1024"
      resources:
        limits:
          cpu: "8"
          memory: "4Gi"
          ibm.com/spyre_pf: "1"
        requests:
          cpu: "8"
          memory: "4Gi"
          ibm.com/spyre_pf: "1"
      runtime: spyre-temp
      storageUri: {{ .Values.reranker.storageUri }}
      args:
      - --served-model-name=BAAI/bge-reranker-v2-m3
      - -tp 1
