apiVersion: v1
kind: Service
metadata:
  name: "digitize-api"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/component: digitize-api
  ports:
    - name: digitize-api
      port: 4000
      targetPort: 4000
      protocol: TCP
