apiVersion: v1
kind: Service
metadata:
  name: "digitize-ui"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/component: digitize-ui
  ports:
    - name: digitize-ui
      port: 4001
      targetPort: 4001
      protocol: TCP
