FROM registry.access.redhat.com/ubi9/ubi:9.6 as docling-builder

WORKDIR /opt/docling-build

RUN     curl "https://raw.githubusercontent.com/ppc64le/build-scripts/c1ea12c200d6ab093a5477acf6c722bc6f36986a/d/docling/opencv_docling_v2.36.0.patch" > opencv_docling_v2.36.0.patch

COPY docling_v2.60.1_ubi9.6.sh .
COPY docling_v2.60.1.patch .
COPY opencv_docling_v2.60.1.patch .
RUN chmod +x docling_v2.60.1_ubi9.6.sh && \
    ./docling_v2.60.1_ubi9.6.sh --skip-tests
RUN ls -lR /opt/docling-build/opencv-python/*.whl

FROM registry.access.redhat.com/ubi9/ubi:9.6

RUN yum install -y git wget gcc gcc-c++ python3-devel pip python3-numpy zlib-devel libjpeg-devel ninja-build libicu-devel lcms2-devel glib2-devel freetype-devel gfortran openblas-devel libxml2-devel libxslt-devel llvm-devel clang-libs

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf config-manager --set-enabled codeready-builder-for-rhel-9-$(arch)-rpms && \
    yum install -y gn geos-devel tesseract-devel spatialindex-devel llvm16-devel ffmpeg-free ffmpeg-free-devel

WORKDIR /opt/wheels
COPY --from=docling-builder /usr/local/lib64/*.so /usr/local/lib64
COPY --from=docling-builder /usr/include/tree_sitter /usr/include/tree_sitter

RUN ln /usr/local/lib64/libopenjp2.so /usr/local/lib64/libopenjp2.so.7
RUN ln -s /usr/lib64/libclang.so.19.1 /usr/lib64/libclang.so
ENV LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
COPY requirements.txt .
COPY download_docling_models.py .

RUN --mount=type=bind,from=docling-builder,source=/opt/docling-build/docling/dist/,target=/opt/wheels/docling-wheels/,ro \
    --mount=type=bind,from=docling-builder,source=/opt/docling-build/opencv-python/,target=/opt/wheels/opencv-wheels/,ro \
    --mount=type=bind,from=docling-builder,source=/opt/docling-build/pytorch/dist/,target=/opt/wheels/torch-wheels/,ro \
    --mount=type=bind,from=docling-builder,source=/opt/docling-build/pypdfium2/,target=/opt/wheels/pypdfium-wheels/,ro \
    --mount=type=bind,from=docling-builder,source=/opt/docling-build/vision/dist/,target=/opt/wheels/torch-vision-wheels/,ro \
    python3 -m venv /var/venv && source /var/venv/bin/activate && \
    pip3 install -r requirements.txt --extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux && \
    python download_docling_models.py
