apiVersion: v1
kind: Service
metadata:
  name: "summarize-api"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/component: summarize-api
  ports:
    - name: summarize-api
      port: 6000
      targetPort: 6000
      protocol: TCP
